import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect , useState } from 'react'
import axios from 'axios'
import Navbar from '../components/Navbar'
import { Container, Card, Row, Text , Button } from "@nextui-org/react";
import { Center } from '@chakra-ui/react'
export default function Home() {


      useEffect(()=>{
        axios.get('http://localhost:8080/')
        .then(res=>{
          console.log(res.data);
        })
      })







  return (
    <div className={styles.container}>
      <Head>
        <title>Eventer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Navbar />

      <main className={styles.main}>
      <Container className={styles.header}>
         <Text  h1 size={19}  color="black" css={{ m: 0 , textAlign: 'Center'}}>
             The Easiest and Most Powerful Online Event Booking and Ticketing System .
          </Text>
          <div className={styles.centerHeader}>
            <Text h6 size={15} color="black" css={{ m: 0 , w: '70%' , textAlign: 'Center'}}>
              Eventer is an all-in-one event ticketing platform for event organisers, promoters, and managers. Easily create, promote and manage your events of any type and size.
            </Text>
          </div>
            <div className={styles.centerHeader}>
                  <Button color="gradient" auto ghost>
                    Success
                  </Button>
            </div>
              
      </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
